project_id = "taetxohwuuzufmkzpzhb"

[functions.woocommerce-orders]
verify_jwt = true

[functions.woocommerce-orders-detailed]
verify_jwt = true

[functions.google-places-pharmacies]
verify_jwt = true

[functions.populate-geography]
verify_jwt = true

[functions.geocode-pharmacies]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.create-customer-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.process-integration-sync-jobs]
verify_jwt = true
